---
title: "subcorridors"
author: "Andrew Simpson"
date: "12/14/2021"
output: html_document
params:
  subcorridor_results_line
---

```{r , include=FALSE}
knitr::opts_chunk$set(echo = TRUE)

library(tidyverse)
```
### `r subcorridor_results_line$corridor_name` Analytics 

Interpretation 

#### Subcorridor Daily Analytics
```{r echo=FALSE}

table_1 <- subcorridor_results_line$route_analytics[[1]] %>% 
  bind_rows(subcorridor_results_line$analytics[[1]] %>% mutate(route_id = "Total"))
  
kable(table_1, booktabs = TRUE, align = 'c',format.args = list(big.mark = ","),digits=1) %>%
 kable_styling(latex_options = "scale_down")  %>%
 row_spec(dim(table_1)[1], bold = T) %>% # format last row
 column_spec(1, italic = T) %>%  # format first column
 scroll_box(width = "100%")
```

#### Weekday Ridership

```{r , echo=FALSE, out.width='100%', fig.height = 5, warning=FALSE}
subcorridor_results_line$ridership_by_period_plot[[1]]
subcorridor_results_line$ridership_by_route_plot[[1]]
subcorridor_results_line$ridership_by_route_dir_plot[[1]]

```

#### Speed and Reliability


##### Speed

```{r , echo=FALSE, out.width='100%', fig.height = 5, warning=FALSE}

subcorridor_results_line$hourly_speed_plot[[1]]
subcorridor_results_line$speed_by_period_plot[[1]]
subcorridor_results_line$speed_by_route_dir_plot[[1]]

```

##### Reliability

```{r , echo=FALSE, out.width='100%', fig.height = 5, warning=FALSE}

dat <- subcorridor_results_line[1, ]$dat %>% 
  as.data.frame()

# get subcorridor specific pattern codings - 
#   in practice, this means that subcorridors will have as many or more primary patterns than full corrides, since some patterns are "primary" on a subcorridor but not on the full corridor
primary_patterns <- code_patterns(subcorridor_results_line$dat[[1]]) %>% filter(pattern_type == "primary") %>% select(pattern_id) %>% as.list()

f <- function(route_num, direction) {
  p <- plot_joyplot_runtimes(dat, route_num = route_num, direction = direction, pattern_list = primary_patterns[[1]], corridor_name = subcorridor_results_line$corridor_name[[1]])
  
  return(p)
  
}
  
reliability_board <- dat %>% 
  group_by(route_id, direction_id) %>% 
  summarise() %>% 
  mutate(joyplot = map2(route_id, direction_id, f))


reliability_board$joyplot


```



#### End-to-End Travel Time

```{r , echo=FALSE, out.width='100%', fig.height = 5, warning=FALSE}

subcorridor_results_line$running_time_dir_plot[[1]]

```