---
title: "Todo List"
author: "Andrew Simpson"
date: "12/17/2021"
output: html_document
---

# Doing

- Add charts that compare subcorridors
- Automate remaining text in document

# Next to-dos

- Convert other tables to reactables & try to add "export" option
- Add stop level charts 
- Add subcorridor ID to stops
- Clean up the corridor/subcorridor input process
- Standardize & functionalize chart formatting 
- Fully implement smarter stop ordering throughout code
- Split Trips by hour into route/direction and show it as average frequency 
- Add average line to hourly/speed chart
- Create a runtimes by passenger boards/alights chart 
- Create a ridership chart showings ons/offs
- Add more subcorridor comparison charts 


# Roadmap

## Near term
- Create corridor level map for top of document
- Create app_v2 to allow user input
- Develop diagramatic view of data at stop/link level - showing lines between stops for speed/running time and points at stops for ons/offs and dwell

## Longer term
- integrate Swiftly AVL data into tool
- create output to "save" for future before/after analysis
- create output to take to predictive tool

# Done

- Create joyplot of runtimes
- Create functions to assist in filtering of route patterns 
- Add filtering of patterns - need to QAQC
- Add reliability charts to subcorridor documents 
