---
title:  "An Analysis of ____ Segment"
author: "Andrew Simpson"
date: "7/18/2020"
output: pdf_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)

source("./code/segmentation_code.R", local = knitr::knit_global())

library(tidyverse)
library(reactable) ; library(shiny)
library(sf) ; library(sp)
library(tidyverse)
library(rgeos)
library(xlsx)

```

```{r analytics, include=FALSE}
apc_data <- read.csv("./data/combined_apc_dataset.csv") %>%  mutate(stop_id = paste0(agency_id, stop_id))
stop_list <- list("SEPTA14084", "SEPTA14085", "SEPTA14086", "SEPTA14088", "SEPTA14089", "SEPTA131")
trip_dat <- suppressWarnings(find_trip_dat_v2(apc_data, stop_list))
print(trip_dat)

analytics <- suppressWarnings(analyze_segment(trip_dat))
route_analytics <- suppressWarnings(analyze_segment_route(trip_dat))
binned_analytics <- suppressWarnings(analyze_segment_hourbin(trip_dat))
hourly_analytics <- suppressWarnings(analyze_segment_hourly(trip_dat))
hourly_route_analytics <- suppressWarnings(analyze_segment_route_hourly(trip_dat))
hourly_route_direction_analytics <- suppressWarnings(analyze_segment_route_direction_hourly(trip_dat))

```

## Segment Data

```{r pressure, echo=FALSE}


```


